stages:
  train:
    cmd: python train.py
    deps:
      - train.py
      - requirements.txt
    outs:
      - model.keras
    metrics:
      - metrics/metrics.json: { cache: false }
    plots:
      - metrics/metrics.csv: { cache: false }