stages:
  train:
    cmd: python train.py
    deps:
      - train.py
      - requirements.txt
    outs:
      - model.keras
    metrics:
      - metrics.json
    # plots:
    #   - metrics.csv:
    #       y: [val_loss, val_acc]