stages:
  train:
    cmd: python train.py
    deps:
    - train.py
    - requirements.txt
    outs:
    - model.h5
    - metrics/confusion_matrix.png
    metrics:
    - metrics/metrics.json: {cache: false}
    plots:
    - metrics/metrics.csv: {cache: false}
