stages:
  train:
    cmd: python train.py
    deps:
      - train.py
      - requirements.txt
    metrics:
      - metrics/metrics.json: { cache: false }
    plots:
      - metrics/metrics.csv: { cache: false }
    # plots:
    #   - metrics.csv:
    #       y: [val_loss, val_acc]