name: CML & DVC
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v2
      - uses: iterative/setup-dvc@v1
      - name: Train model
        env:
          DAGSHUB_ACCESS_TOKEN: ${{ secrets.DAGSHUB_ACCESS_TOKEN }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_NAME: ${{ secrets.GIT_NAME }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro
      - name: Configure DVC remote
        run: |
          dvc remote modify origin access_key_id ${{ secrets.DVC_ACCESS_KEY_ID }}
          dvc remote modify origin secret_access_key ${{ secrets.DVC_SECRET_ACCESS_KEY }}
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          echo "## Metrics: workflow vs. master" >> report.md
          git fetch --prune --unshallow
          dvc metrics diff master --md  >> report.md
          echo "## Plots" >> report.md
          dvc plots diff master  >> report.md
          echo "![Confusion Matrix](./metrics/confusion_matrix.png)" >> report.md
          cml comment create report.md
          dvc push
          cml pr create --merge --skip-ci --title "Automated: DVC meta file update [skip ci]" dvc.lock